### ISSUE TITLE
test build fails with new go.mod

### ISSUE THREAD

**Issue by raulk** [libp2p/go-libp2p-examples#47]
Introduced in #40:

```
go: downloading github.com/jackpal/go-nat-pmp v1.0.1
go: downloading golang.org/x/text v0.3.0
go: downloading github.com/whyrusleeping/mdns v0.0.0-20180901202407-ef14215e6b30
go: finding github.com/miekg/dns v1.1.4
go: downloading github.com/miekg/dns v1.1.4
# github.com/miekg/dns
../../../../pkg/mod/github.com/miekg/dns@v1.1.4/dnssec_keyscan.go:184:18: undefined: ed25519.SeedSize
../../../../pkg/mod/github.com/miekg/dns@v1.1.4/dnssec_keyscan.go:187:8: undefined: ed25519.NewKeyFromSeed
../../../../pkg/mod/github.com/miekg/dns@v1.1.4/dnssec_privkey.go:85:24: p.Seed undefined (type ed25519.PrivateKey has no field or method Seed)
```

CircleCI: https://circleci.com/gh/libp2p/go-libp2p-examples/12
