### ISSUE TITLE
types error when build mdns

### ISSUE THREAD

**Issue by JackBekket** [libp2p/go-libp2p-examples#67]
```
cannot use peerhost (type "github.com/libp2p/go-libp2p-core/host".Host) as type "github.com/libp2p/go-libp2p-host".Host in argument to discovery.NewMdnsService:
	"github.com/libp2p/go-libp2p-core/host".Host does not implement "github.com/libp2p/go-libp2p-host".Host (wrong type for ConnManager method)
		have ConnManager() connmgr.ConnManager
		want ConnManager() ifconnmgr.ConnManager
```

**Comment by JackBekket** [comment]
when I try `go get -v -d ./...`
and then `go build`
it's says

```
# github.com/libp2p/go-libp2p/p2p/host/routed
../../github.com/libp2p/go-libp2p/p2p/host/routed/routed.go:190:5: cannot use (*RoutedHost)(nil) (type *RoutedHost) as type host.Host in assignment:
	*RoutedHost does not implement host.Host (missing EventBus method)
# github.com/libp2p/go-libp2p/p2p/host/basic
../../github.com/libp2p/go-libp2p/p2p/host/basic/basic_host.go:83:5: cannot use (*BasicHost)(nil) (type *BasicHost) as type host.Host in assignment:
	*BasicHost does not implement host.Host (missing EventBus method)
../../github.com/libp2p/go-libp2p/p2p/host/basic/basic_host.go:148:64: cannot use h (type *BasicHost) as type host.Host in argument to identify.NewIDService:
	*BasicHost does not implement host.Host (missing EventBus method)
../../github.com/libp2p/go-libp2p/p2p/host/basic/basic_host.go:175:32: cannot use h (type *BasicHost) as type host.Host in argument to ping.NewPingService:
	*BasicHost does not implement host.Host (missing EventBus method)
```

**Comment by JackBekket** [comment]
I'm working on this
https://github.com/MoonSHRD/p2chat/tree/refactor/pubsub

**Comment by Kubuxu** [comment]
Hi, downgrade to `go-libp2p-core@v0.0.3` by adding:
```
replace github.com/libp2p/go-libp2p-core => github.com/libp2p/go-libp2p-core@v0.0.3
```

To your main go file.

**Comment by JackBekket** [comment]
thanks! 

Also I've noticed, that new modules worked with 1.12 go version, I has 1.11
